### ISSUE TITLE
Conflict with latest release of scipy

### ISSUE THREAD

**Issue by GregoryAshton** [bfarr/kombine#29]
Hi @bfarr, our bilby CI tests have picked up a conflict between kombine and the latest scipy (v1.7.0) release. The test works under scipy v1.5.0 (I haven't tested releases in between).

Here is the traceback for debugging. It looks like it is the automatic burn-in process causing the issue.

```
Traceback (most recent call last):
  File "test/integration/sampler_run_test.py", line 94, in test_run_kombine
    _ = bilby.run_sampler(
  File "/home/greg/bilby/bilby/core/sampler/__init__.py", line 186, in run_sampler
    result = sampler.run_sampler()
  File "/home/greg/bilby/bilby/core/sampler/kombine.py", line 138, in run_sampler
    self.sampler.burnin(**self.sampler_burnin_kwargs)
  File "/home/greg/software/anaconda3/envs/bilby/lib/python3.8/site-packages/kombine/sampler.py", line 262, in burnin
    if self.consistent_acceptance_rate(window_size=step_size*act, critical_pval=critical_pval):
  File "/home/greg/software/anaconda3/envs/bilby/lib/python3.8/site-packages/kombine/sampler.py", line 743, in consistent_acceptance_rate
    _, p_val = chisquare(nacc, expected_freqs)
  File "/home/greg/software/anaconda3/envs/bilby/lib/python3.8/site-packages/scipy/stats/stats.py", line 6852, in chisquare
    return power_divergence(f_obs, f_exp=f_exp, ddof=ddof, axis=axis,
  File "/home/greg/software/anaconda3/envs/bilby/lib/python3.8/site-packages/scipy/stats/stats.py", line 6694, in power_divergence
    raise ValueError(msg)
ValueError: For each axis slice, the sum of the observed frequencies must agree with the sum of the expected frequencies to a relative tolerance of 1e-08, but the percent differences are:
0.14893617021276595
```

**Comment by Gabriel-p** [comment]
The issue was (is?) debated here: https://github.com/scipy/scipy/issues/14298

**Comment by mdhaber** [comment]
Yes. A more complete discussion about this issue is in scipy/scipy#12282.
